"""initial_refactor

Revision ID: ced0365fbb3d
Revises:
Create Date: 2026-08-12 14:12:22.472363
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ced0365fbb3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('videos',
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('source_uri', sa.String(length=1024), nullable=True),
    sa.Column('normalized_uri', sa.String(length=1024), nullable=True),
    sa.Column('audio_uri', sa.String(length=1024), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fps_num', sa.Integer(), nullable=True),
    sa.Column('fps_den', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('audio_sample_rate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('scenes',
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('shot_ids', sa.JSON(), nullable=True),
    sa.Column('boundary_confidence', sa.Float(), nullable=True),
    sa.Column('scene_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('scene_id')
    )
    op.create_table('shots',
    sa.Column('shot_id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('start_frame', sa.Integer(), nullable=True),
    sa.Column('end_frame_exclusive', sa.Integer(), nullable=True),
    sa.Column('boundary_type', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('shot_id')
    )
    op.create_table('subtitle_segments',
    sa.Column('subtitle_id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('subtitle_id')
    )
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('workflow_run_id', sa.String(length=32), nullable=True),
    sa.Column('task_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('executor_run_id', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('model_runs',
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('code_revision', sa.String(length=128), nullable=True),
    sa.Column('weight_revision', sa.String(length=128), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('parameters_json', sa.JSON(), nullable=True),
    sa.Column('cache_key', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('scene_evidence',
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('scene_id', sa.String(length=32), nullable=False),
    sa.Column('visual_continuity', sa.Float(), nullable=True),
    sa.Column('character_continuity', sa.Float(), nullable=True),
    sa.Column('location_continuity', sa.Float(), nullable=True),
    sa.Column('subtitle_continuity', sa.Float(), nullable=True),
    sa.Column('audio_continuity', sa.Float(), nullable=True),
    sa.Column('temporal_gap_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.scene_id'], ),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    op.create_table('workflow_runs',
    sa.Column('workflow_run_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=32), nullable=False),
    sa.Column('workflow_name', sa.String(length=64), nullable=False),
    sa.Column('workflow_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.task_id'], ),
    sa.PrimaryKeyConstraint('workflow_run_id')
    )
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('producer_run_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_type', sa.String(length=64), nullable=False),
    sa.Column('uri', sa.String(length=1024), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['producer_run_id'], ['model_runs.run_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.video_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('model_run_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('input_role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_run_outputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('output_role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['model_runs.run_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_run_outputs')
    op.drop_table('model_run_inputs')
    op.drop_table('artifacts')
    op.drop_table('workflow_runs')
    op.drop_table('scene_evidence')
    op.drop_table('model_runs')
    op.drop_table('tasks')
    op.drop_table('subtitle_segments')
    op.drop_table('shots')
    op.drop_table('scenes')
    op.drop_table('videos')
    op.drop_table('projects')
    # ### end Alembic commands ###
